// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNYibyVjuD0B4CLDlV5MtCriR8Zf69UE',
    appId: '1:309451813171:web:709fb91e95e3697e7a0e46',
    messagingSenderId: '309451813171',
    projectId: 'terdom-dcc61',
    authDomain: 'terdom-dcc61.firebaseapp.com',
    storageBucket: 'terdom-dcc61.firebasestorage.app',
    measurementId: 'G-SEF19XL250',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtz2s-pa1fk_I6Vrg2KhS5CotQRM9v3k',
    appId: '1:309451813171:android:fbf0458cab84ba3b7a0e46',
    messagingSenderId: '309451813171',
    projectId: 'terdom-dcc61',
    storageBucket: 'terdom-dcc61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJxMDYQANbYbQQdS3kRS_-OJl5_fO0ls',
    appId: '1:309451813171:ios:03eb11b997176d197a0e46',
    messagingSenderId: '309451813171',
    projectId: 'terdom-dcc61',
    storageBucket: 'terdom-dcc61.firebasestorage.app',
    iosBundleId: 'com.example.ternak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJxMDYQANbYbQQdS3kRS_-OJl5_fO0ls',
    appId: '1:309451813171:ios:03eb11b997176d197a0e46',
    messagingSenderId: '309451813171',
    projectId: 'terdom-dcc61',
    storageBucket: 'terdom-dcc61.firebasestorage.app',
    iosBundleId: 'com.example.ternak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNYibyVjuD0B4CLDlV5MtCriR8Zf69UE',
    appId: '1:309451813171:web:f6b89dbcd99e97a07a0e46',
    messagingSenderId: '309451813171',
    projectId: 'terdom-dcc61',
    authDomain: 'terdom-dcc61.firebaseapp.com',
    storageBucket: 'terdom-dcc61.firebasestorage.app',
    measurementId: 'G-4ZNK0KL3LD',
  );
}
